# Generated by Django 4.2.3 on 2023-10-23 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("translate", "seed_languages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dictionary",
            options={"verbose_name_plural": "Dictionaries"},
        ),
    ]
